FootballAnalysisUI/Controllers/HomeController.cs
using FootballAnalysisUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FootballAnalysisUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FootballAnalysisUI/Controllers/SeasonController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;

namespace FootballAnalysisUI.Controllers
{
    public class SeasonController : Controller
    {
        public IActionResult Index()
        {
            SeasonManager sm = new SeasonManager(new EfSeasonDal());
            return View(sm.ListAll().OrderByDescending(x=> x.SeasonYear).ToList());
        }
    }
}

FootballAnalysisUI/Controllers/TeamController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FootballAnalysisUI.Models;
using HtmlAgiltyPack.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FootballAnalysisUI.Controllers
{
    public class TeamController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AllTeamMatches(int ID)
        {
            TeamInfoManager teamInfoManager = new TeamInfoManager(new EFTeamInfoDal());
            var teamInfos = teamInfoManager.ListAll();
            HAPMatchScoreDal hAPMatchScoreDal = new HAPMatchScoreDal(teamInfos.FirstOrDefault(x => x.ID == ID));
            return View(hAPMatchScoreDal.GetAllMatchScores());
        }

        public IActionResult TeamList()
        {
            TeamInfoManager teamInfoManager = new TeamInfoManager(new EFTeamInfoDal());
            var teamInfos = teamInfoManager.ListAll().OrderBy(x=> x.RealTeamName).ToList();
            return View(teamInfos);
        }

        [HttpGet]
        public IActionResult TeamvsTeam()
        {
            TeamInfoManager teamInfoManager = new TeamInfoManager(new EFTeamInfoDal());
            var teamInfos = teamInfoManager.ListAll().OrderBy(x => x.RealTeamName).ToList();
            List<SelectListItem> selectListItems = new List<SelectListItem>();
            foreach (var item in teamInfos)
            {
                selectListItems.Add(new SelectListItem { Text = item.RealTeamName, Value = item.ID.ToString() });
            }
            return View(selectListItems);
        }
        [HttpPost]
        public IActionResult AllTeamMatchesBetweenTwoTeam(string team1, string team2)
        {
            TeamInfoManager teamInfoManager = new TeamInfoManager(new EFTeamInfoDal());
            var teamInfos = teamInfoManager.ListAll();
            HAPMatchScoreDal hAPMatchScoreDalTeamOne = new HAPMatchScoreDal(teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team1)));
            HAPMatchScoreDal hAPMatchScoreDalTeamTwo = new HAPMatchScoreDal(teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team2)));
            List<MatchScore> matchList = new List<MatchScore>();
            matchList.AddRange(hAPMatchScoreDalTeamOne.GetAllMatchScores().Where(x => x.OpponentName == teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team2)).RealTeamName).ToList());
            matchList.AddRange(hAPMatchScoreDalTeamTwo.GetAllMatchScores().Where(x => x.OpponentName == teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team1)).RealTeamName).ToList());
            List<MatchScore> listedMatchList = matchList.OrderByDescending(MatchScore => Convert.ToDateTime(MatchScore.date)).ToList();

            return View(listedMatchList);
        }

        public IActionResult DetailedTeamvsTeam(string team1, string team2)
        {
            TeamInfoManager teamInfoManager = new TeamInfoManager(new EFTeamInfoDal());
            var teamInfos = teamInfoManager.ListAll();
            Compare cmp = new Compare();
            cmp.TeamOneID = Convert.ToInt16(team1);
            cmp.TeamTwoID = Convert.ToInt16(team2);

            cmp.TeamOneName = teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team1)).RealTeamName;
            cmp.TeamTwoName = teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team2)).RealTeamName; ;
            cmp.TeamOneURLNumber = teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team1)).InUrlTeamNumber;
            cmp.TeamTwoURLNumber = teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team2)).InUrlTeamNumber;
            HAPMatchScoreDal hAPMatchScoreDalTeamOne = new HAPMatchScoreDal(teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team1)));
            HAPMatchScoreDal hAPMatchScoreDalTeamTwo = new HAPMatchScoreDal(teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team2)));

            List<MatchScore> matchListTeamOne = hAPMatchScoreDalTeamOne.GetAllMatchScores().Where(x => x.OpponentName == teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team2)).RealTeamName).ToList();
            List<MatchScore> matchListTeamTwo = hAPMatchScoreDalTeamTwo.GetAllMatchScores().Where(x => x.OpponentName == teamInfos.FirstOrDefault(x => x.ID == Convert.ToInt16(team1)).RealTeamName).ToList();

            foreach (var item in matchListTeamOne)
            {
                cmp.TeamOneGoalinHome += item.HomeScore;
                cmp.TeamTwoGoalinAway += item.OpponentScore;

                if (item.HomeScore == item.OpponentScore)
                {
                    cmp.TeamOneHomeDraw += 1;
                }
                else if (item.HomeScore > item.OpponentScore)
                {
                    cmp.TeamOneWininHome += 1;
                }
                else
                {
                    cmp.TeamTwoWininAway += 1;
                }
                cmp.MatchCount += 1;
            }

            foreach (var item in matchListTeamTwo)
            {
                cmp.TeamOneGoalinAway += item.OpponentScore;
                cmp.TeamTwoGoalinHome += item.HomeScore;

                if (item.HomeScore == item.OpponentScore)
                {
                    cmp.TeamTwoHomeDraw += 1;
                }
                else if (item.HomeScore > item.OpponentScore)
                {
                    cmp.TeamTwoWininHome += 1;
                }
                else
                {
                    cmp.TeamOneWininAway += 1;
                }
                cmp.MatchCount += 1;
            }
            cmp.DrawCount = cmp.TeamOneHomeDraw + cmp.TeamTwoHomeDraw;
            cmp.TeamOneGoalAll = cmp.TeamOneGoalinHome + cmp.TeamOneGoalinAway;
            cmp.TeamTwoGoalAll = cmp.TeamTwoGoalinHome + cmp.TeamTwoGoalinAway;
            cmp.GoalAll = cmp.TeamOneGoalAll + cmp.TeamTwoGoalAll;
            cmp.TeamOneWinAll = cmp.TeamOneWininHome + cmp.TeamOneWininAway;
            cmp.TeamTwoWinAll = cmp.TeamTwoWininHome + cmp.TeamTwoWininAway;

            return View(cmp);
        }
    }
}

FootballAnalysisUI/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Süper Lig Analiz</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="mt-4 p-5 bg-white text-white rounded">
                <div class="row">
                    <div class="col-9">
                        <h1 class="text-black">Türkiye Süper Ligi Analiz ve İstatistik</h1>
                        <p class="text-black">Futbol ve verilerin dünyasına hoş geldiniz.</p>
                    </div>
                    <div class="col-3">
                        <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/tr/e/ef/S%C3%BCper_Lig_logo.png?20210222141944" style="width:180px">
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col">
                <div class="card" style="width:400px">
                    <center>
                        <img class="card-img-top" src="assets/img/champion.png" alt="Card image" style="width:57%">
                        <div class="card-body">
                            <h4 class="card-title">Sezon Bilgileri</h4>
                            <p class="card-text">Sezonlara göre şampiyon ve gol kralı bilgileri</p>
                            <a asp-controller="Season" asp-action="Index" class="btn btn-primary">Git</a>
                        </div>
                    </center>
                </div>
            </div>
            <div class="col">
                <div class="card" style="width:400px">
                    <center>
                        <img class="card-img-top" src="assets/img/vs.png" style="width:60%" />
                        <div class="card-body">
                            <h4 class="card-title">İki Takım Arası Veriler</h4>
                            <p class="card-text">İki takım arasında yapılan karşılaşmalar, atılan-yenilen goller ve daha fazlası.</p>
                            <a asp-controller="Team" asp-action="TeamvsTeam" class="btn btn-primary">Git</a>
                        </div>
                    </center>
                </div>
            </div>
            <div class="col">
                <div class="card" style="width:400px">
                    <center>
                    <img class="card-img-top" src="assets/img/teamlist.png" alt="Card image" style="width:55%">
                    <div class="card-body">
                        <h4 class="card-title">Takım Listesi</h4>
                        <p class="card-text">Takımların listesi ve seçilen takımın tüm maçları.</p>
                            <a asp-controller="Team" asp-action="TeamList" class="btn btn-primary">Git</a>
                    </center>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>